<?php
/*
 * David Bray
 * BrayWorth Pty Ltd
 * e. david@brayworth.com.au
 *
 * MIT License
 *
*/  ?>

<footer class="fixed-bottom">
  <div class="container-fluid">
    <div class="row mb-0">
      <div class="col text-muted"></div>

      <div class="col-auto" id="brayworthLOGO">
        <a title="software by BrayWorth using php" href="https://brayworth.com" target="_blank">BrayWorth</a>

      </div>

    </div>

  </div>

</footer>
