<html>

<head>
  <title><?= $title ?></title>
  <link type="text/css" rel="stylesheet" media="all" href="/css/bootstrap.min.css" />
  <link type="text/css" rel="stylesheet" media="all" href="/css/bootstrap-icons.css" />
  <script src="/js/jquery.min.js"></script>

</head>

<body>
  <?= $this->fetch('navbar.phtml'); ?>

  <div class="container">
    <div class="row">
      <div class="col-auto mx-auto my-4">
        <h1 class="bi bi-house"></h1>

      </div>

    </div>

  </div>

  <?= $this->fetch('footer.phtml'); ?>

  <script src="/js/bootstrap.min.js"></script>
</body>

</html>